### ISSUE TITLE
Bad voxelisation with version 237c3b8

### ISSUE THREAD

**Issue by elombardi2** [dcoeurjo/pc2vol#3]
pc2vol version 237c3b8 produces bad voxelisation, for example with [bimba_original_meshlab_normals_v5.xyz.zip](https://github.com/dcoeurjo/pc2vol/files/14790049/bimba_original_meshlab_normals_v5.xyz.zip).

Command line to reproduce the issue:
`pc2vol -i  bimba_original_meshlab_normals_v5.xyz  --gridstep 0.025  -o bimba_original_meshlab_normals_v5.vol`

Normal output (pc2vol version 0b7250e):
![Capture d’écran du 2024-03-28 13-57-34](https://github.com/dcoeurjo/pc2vol/assets/11190899/8c542ae4-ffde-4bb9-9ab6-511e4e7edf4a)

Broken output (pc2vol version 237c3b8):
![Capture d’écran du 2024-03-28 14-05-39](https://github.com/dcoeurjo/pc2vol/assets/11190899/d6bbdddb-2a83-4701-b1eb-5add172ccc25)

**Comment by dcoeurjo** [comment]
Yes that's "normal". Skipping CGAL implies a better control of the scale factor of point areas. I've refactored the code to explicit this parameter

**Comment by dcoeurjo** [comment]
ok done, new option: `--skipCGALAreas` and `--factor`.
Gridstep and factor is now in IMGUI sliders (visu mode)

**Comment by dcoeurjo** [comment]
I was able to voxelize bimba with the new version (grid step == factor == 0.01)

**Comment by dcoeurjo** [comment]
It should do the job for uniform density samples. I would have something smarter to do for non-unit points
